# Generated by Django 3.1.7 on 2021-04-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_remove_producto_origen_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
